<a href="https://colab.research.google.com/github/omkarpattnaik8080/NUMPY01/blob/main/NumpyComplete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [19]:
np.__version__


'1.23.5'

In [20]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [3]:
l=[3,4,5,6,7]

In [4]:
print(l)

[3, 4, 5, 6, 7]


In [21]:
#convert the list into an array
array=np.array(l)

In [22]:
type(np.array(l))

numpy.ndarray

In [23]:
#for knowing the dimension of array
array.ndim


1

In [13]:
l=[1,2,3,4,"omkar"]

In [24]:
arr1=np.array(l)

In [25]:
arr1

array(['1', '2', '3', '4', 'omkar'], dtype='<U21')

In [29]:
#2d array
arr11=np.array([[1,2,3],[4,5,6]])

In [30]:
arr11

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr11.ndim

2

In [32]:
#Matrix:-
l=[1,2,3,4]

In [33]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [34]:
np.asarray(l)

array([1, 2, 3, 4])

In [36]:
#conversion of tupple into an array:-
t=([1,2,3],[4,5,6])
type(t)

tuple

In [37]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
#conversion of a scaler into an array
a=8
np.array(a)

array(8)

In [40]:
list=[3,4,5,6]
arr=np.array(list)

In [41]:
arr

array([3, 4, 5, 6])