<a href="https://colab.research.google.com/github/omkarpattnaik8080/NUMPY01/blob/main/NumpyComplete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
np.__version__


'1.25.2'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [ ]:
l=[3,4,5,6,7]

In [ ]:
print(l)

[3, 4, 5, 6, 7]


In [ ]:
#convert the list into an array
array=np.array(l)

In [ ]:
type(np.array(l))

numpy.ndarray

In [ ]:
#for knowing the dimension of array
array.ndim


1

In [ ]:
l=[1,2,3,4,"omkar"]

In [ ]:
arr1=np.array(l)

In [ ]:
arr1

array(['1', '2', '3', '4', 'omkar'], dtype='<U21')

In [ ]:
#2d array
arr11=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr11

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr11.ndim

2

In [ ]:
#Matrix:-
l=[1,2,3,4]

In [ ]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
#conversion of tupple into an array:-
t=([1,2,3],[4,5,6])
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#conversion of a scaler into an array
a=8
np.array(a)

array(8)

In [ ]:
list=[3,4,5,6]
arr=np.array(list)

In [ ]:
arr

array([3, 4, 5, 6])

In [ ]:
#OTHER WAYS TO GENERATE AN ARRAY
np.fromfunction(lambda i,j:i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
#the number of elements in an array
arr.size

4

In [ ]:
np.fromfunction(lambda i,j:i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
#from the iterables also array can be generated
iterable=(i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#from the string also array can be generated
np.fromstring("1,2,3,4",sep=",")

array([1., 2., 3., 4.])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#range cannot deal with float variable
list(range(1.0,2,10))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
#when we have a fraction value in numpy we do:-
np.arange(0.1,10.2,0.2) #here 0.2 is the jump and read as START from 0.1 AND END AT 10.2

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [ ]:
np.linspace(1,5,20)#read as "GENERATE THE VALUE THAT START FROM 1 & ENDS WITH 5 AND THEN GIVE ME 20 VALUES BTW 1 TO 5"

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,10,base=2)#start from 1 end at 5 and total of 10 numbers btw them  with log of each with a base of two

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
#zeros
arr1=np.zeros(5)
arr1.shape

(5,)

In [ ]:
arr2=np.zeros((3,4)) #read as 3 rows and 4 columns
arr2.shape

(3, 4)

In [ ]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
#all the numbers interms of ones:-
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr=np.ones((3,4))

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#if you want to add 5 to all the elements of the array
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
#numpy advanvce:-
arr=np.ones((3,4))#3 rows and 4 columns

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3,4))#it will give us an array but with some random values,

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
#if we use int in the above the decimal will get converted to the integer
np.empty((3,4),int)

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [ ]:
#eye generates digonal matrix with 1 in digonal and 0 elsewhere:-
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [ ]:
#extra topics
import random #random can generate random numbers

In [ ]:
random.choice((1,2,3,45,6))

2

In [ ]:
random.choice("Ajay")

'a'

In [ ]:
#for generating a random number in the range:-
random.randrange(1,10)

6

In [ ]:
#if i want 3 random numbers btw 1 to 10:-
random.randrange(1,10,3)

7

In [ ]:
#for shuffling the values
list=[1,2,3,4,5]
random.shuffle(list)

In [ ]:
list

[5, 2, 1, 3, 4]

In [ ]:
#for uniform distribution
random.uniform(7,14)

13.24338040635782

In [ ]:
random.random()#a random number generated between a(included), 1 will be excluded

0.4386024137027519

In [ ]:
#when numpy came it said y to use different library use numpy instead
np.random.rand(2,3)

array([[0.31275225, 0.83406819, 0.12860912],
       [0.74545452, 0.3954235 , 0.54171302]])

In [ ]:
np.random.rand(1)

array([0.81083663])

In [ ]:
#for normal distribution:-
np.random.randn(2,3)

array([[ 0.03717535, -1.0946235 , -0.61835373],
       [ 0.29304491, -0.4825278 ,  0.20013765]])

In [ ]:
#to get anything btw zero and one
np.random.random_sample()

0.7986930620199376

In [ ]:
#generate random integer from 1 to 5 with 3 rows and 4 columns
np.random.randint(1,5,size=(3,4))

array([[4, 1, 4, 4],
       [3, 2, 1, 2],
       [3, 1, 1, 2]])

In [ ]:
arr=np.random.randint(1,5,size=(3,4))

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.reshape(2,6) #arraysize cannot change,multiples of array size

array([[2, 1, 4, 1, 2, 2],
       [1, 3, 1, 3, 2, 3]])

In [ ]:
#if u want 1 dimension:-
arr.reshape(12)

array([2, 1, 4, 1, 2, 2, 1, 3, 1, 3, 2, 3])

In [ ]:
#you know the rows but you dont have the idea about the columns Numpy will automatically take care of it:-
arr.reshape(4,-1)

array([[2, 1, 4],
       [1, 2, 2],
       [1, 3, 1],
       [3, 2, 3]])

In [ ]:
#inpace of -1 if we put any value it will treat it as -1 only
arr.reshape(4,-1000)

array([[2, 1, 4],
       [1, 2, 2],
       [1, 3, 1],
       [3, 2, 3]])

In [ ]:
#you atleast have to know about one dimension
arr.reshape(-1,3)

array([[2, 1, 4],
       [1, 2, 2],
       [1, 3, 1],
       [3, 2, 3]])

In [ ]:
arr.reshape(3,4).base #base bascially means what is the original array

array([[2, 1, 4, 1],
       [2, 2, 1, 3],
       [1, 3, 2, 3]])

In [ ]:
arr #the original array and above is the same as the original array

array([[2, 1, 4, 1],
       [2, 2, 1, 3],
       [1, 3, 2, 3]])

In [ ]:
arr.reshape(2,2,3)

array([[[2, 1, 4],
        [1, 2, 2]],

       [[1, 3, 1],
        [3, 2, 3]]])

In [ ]:
#when there are 3 dimension as parameter
arr.reshape(2,2,3) #2 rows and 3 columns repeated 2 times

array([[[2, 1, 4],
        [1, 2, 2]],

       [[1, 3, 1],
        [3, 2, 3]]])

In [ ]:
#Dimensions:-
lis=[1,2,3,4]
arr=np.array(lis)

In [ ]:
arr.ndim

2

In [ ]:
arr2=np.array([[2,3],[4,5]])
arr2

array([[2, 3],
       [4, 5]])

In [ ]:
arr2.ndim

2

In [ ]:
arr2=np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr3=np.zeros((1,3,4)) #3rows 4columns and one extra dimension
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr3.ndim

3

In [ ]:
#if we want to have 4 dimensions:-
arr4=np.zeros((1,1,3,4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [ ]:
arr4.ndim

4

In [ ]:
arr3=np.zeros((1,3,4)) #if 1 will be replaced by 2 the dimension wont change only the number of matrix will change
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
arr1=np.random.randint(1,10,(5,6))
arr1

array([[5, 9, 7, 3, 1, 3],
       [5, 5, 3, 7, 7, 4],
       [7, 2, 5, 3, 5, 9],
       [4, 8, 1, 5, 8, 8],
       [4, 8, 5, 7, 1, 6]])

In [ ]:
arr1>5 #it will see index wise element  and check where this condn is true

array([[False,  True,  True, False, False, False],
       [False, False, False,  True,  True, False],
       [ True, False, False, False, False,  True],
       [False,  True, False, False,  True,  True],
       [False,  True, False,  True, False,  True]])

In [ ]:
arr1[arr1>5] #give me all the values in the array where the condition is true vvimp!

array([9, 7, 7, 7, 7, 9, 8, 8, 8, 8, 7, 6])

In [ ]:
arr1<5

array([[False, False, False,  True,  True,  True],
       [False, False,  True, False, False,  True],
       [False,  True, False,  True, False, False],
       [ True, False,  True, False, False, False],
       [ True, False, False, False,  True, False]])

In [ ]:
arr[0]

array([2, 1, 4, 1])

In [ ]:
arr1

array([[5, 9, 7, 3, 1, 3],
       [5, 5, 3, 7, 7, 4],
       [7, 2, 5, 3, 5, 9],
       [4, 8, 1, 5, 8, 8],
       [4, 8, 5, 7, 1, 6]])

In [ ]:
#if u want to access the first row:
arr1[0]

array([5, 9, 7, 3, 1, 3])

In [ ]:
#if you want to have a particular element:-
arr1[0][1]

9

In [ ]:
#if you want to geta slice:-
arr1[0,[1,3]] #we get elements between 1 and 3 and 3 is inclusive

array([9, 3])

In [ ]:
#you want from second row to 4th row and u want 2nd column and 3rd column
arr1[2:4,[2,3]]

array([[5, 3],
       [1, 5]])

In [ ]:
arr1[2:4,[0,2]]

array([[7, 5],
       [4, 1]])

In [ ]:
arr1[2:5] #for the rows from 2 to 5

array([[7, 2, 5, 3, 5, 9],
       [4, 8, 1, 5, 8, 8],
       [4, 8, 5, 7, 1, 6]])

In [ ]:
arr1[2:5,0:2] #slicing

array([[7, 2],
       [4, 8],
       [4, 8]])

In [ ]:
arr1[2:5,[0,2]]

array([[7, 5],
       [4, 1],
       [4, 5]])

In [ ]:
arr1[[2,4],[0,2]]

array([7, 5])

In [ ]:
arr1[[2,4]] #if you want 2nd and 4th row aka selecting specific column

array([[7, 2, 5, 3, 5, 9],
       [4, 8, 5, 7, 1, 6]])

In [ ]:
#if you want from 2nd to 4th row
arr1[2:4]

array([[7, 2, 5, 3, 5, 9],
       [4, 8, 1, 5, 8, 8]])

In [ ]:
arr1[[2,4]]

array([[7, 2, 5, 3, 5, 9],
       [4, 8, 5, 7, 1, 6]])

In [ ]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [ ]:
arr1

array([[1, 2, 2],
       [1, 2, 1],
       [2, 2, 2]])

In [ ]:
arr2

array([[2, 1, 2],
       [1, 1, 1],
       [2, 2, 2]])

In [ ]:
#if you want to add 2 arrays how it can be added:-
arr1+arr2

array([[3, 3, 4],
       [2, 3, 2],
       [4, 4, 4]])

In [ ]:
arr1-arr2 #indexwise subtraction

array([[-1,  1,  0],
       [ 0,  1,  0],
       [ 0,  0,  0]])

In [ ]:
arr1*arr2 #indexwise multiplication this is not the matrix multiplication

array([[2, 2, 4],
       [1, 2, 1],
       [4, 4, 4]])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
#matrix multiplication
arr1@arr2

array([[ 8,  7,  8],
       [ 6,  5,  6],
       [10,  8, 10]])

In [ ]:
#numpy understands infinity
arr1/0

<ipython-input-16-036c798a2c96>:2: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#BROADCASTING:- you are adding or subtracting with each and every row

In [ ]:
arr=np.zeros((3,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
a=np.array([1,2,3])
a=np.array([[1,2,3]]) #making a 2d array

In [ ]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
#TRANSPOSE:-EARLY THAT WAS IN ROW FORMAT IT WILL CONVERT IT TO COLUMN FORMAT
a.T

array([[1],
       [2],
       [3]])

In [1]:
#BINARY MATHEMATICAL OPERATION IN NUMPY:-

In [5]:
data=np.array([[1],[2],[3]])

In [8]:
data

array([[1],
       [2],
       [3]])

In [6]:
#squeeze function:-
np.squeeze(data)

array([1, 2, 3])

In [ ]:
#REPEAT:-
data

In [9]:
np.repeat(data,4) #read as np dot repeat (what will repeat,how many times it will repeat)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [10]:
a=np.array([[1,2],[3,4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [14]:
np.repeat(a,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])