<a href="https://colab.research.google.com/github/omkarpattnaik8080/NUMPY01/blob/main/NumpyComplete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
np.__version__


'1.23.5'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [2]:
l=[3,4,5,6,7]

In [8]:
print(l)

[3, 4, 5, 6, 7]


In [9]:
#convert the list into an array
array=np.array(l)

In [10]:
type(np.array(l))

numpy.ndarray

In [11]:
#for knowing the dimension of array
array.ndim


1

In [ ]:
l=[1,2,3,4,"omkar"]

In [ ]:
arr1=np.array(l)

In [ ]:
arr1

array(['1', '2', '3', '4', 'omkar'], dtype='<U21')

In [ ]:
#2d array
arr11=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr11

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr11.ndim

2

In [ ]:
#Matrix:-
l=[1,2,3,4]

In [ ]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
#conversion of tupple into an array:-
t=([1,2,3],[4,5,6])
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#conversion of a scaler into an array
a=8
np.array(a)

array(8)

In [15]:
list=[3,4,5,6]
arr=np.array(list)

In [16]:
arr

array([3, 4, 5, 6])

In [12]:
#OTHER WAYS TO GENERATE AN ARRAY
np.fromfunction(lambda i,j:i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [17]:
#the number of elements in an array
arr.size

4

In [18]:
np.fromfunction(lambda i,j:i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [19]:
#from the iterables also array can be generated
iterable=(i*i for i in range(5))

In [21]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [24]:
#from the string also array can be generated
np.fromstring("1,2,3,4",sep=",")

array([1., 2., 3., 4.])