<a href="https://colab.research.google.com/github/omkarpattnaik8080/NUMPY01/blob/main/NumpyComplete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
np.__version__


'1.23.5'

In [ ]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [ ]:
l=[3,4,5,6,7]

In [ ]:
print(l)

[3, 4, 5, 6, 7]


In [ ]:
#convert the list into an array
array=np.array(l)

In [ ]:
type(np.array(l))

numpy.ndarray

In [ ]:
#for knowing the dimension of array
array.ndim


1

In [ ]:
l=[1,2,3,4,"omkar"]

In [ ]:
arr1=np.array(l)

In [ ]:
arr1

array(['1', '2', '3', '4', 'omkar'], dtype='<U21')

In [ ]:
#2d array
arr11=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr11

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr11.ndim

2

In [ ]:
#Matrix:-
l=[1,2,3,4]

In [ ]:
np.matrix(l)

matrix([[1, 2, 3, 4]])

In [ ]:
np.asarray(l)

array([1, 2, 3, 4])

In [ ]:
#conversion of tupple into an array:-
t=([1,2,3],[4,5,6])
type(t)

tuple

In [ ]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#conversion of a scaler into an array
a=8
np.array(a)

array(8)

In [ ]:
list=[3,4,5,6]
arr=np.array(list)

In [ ]:
arr

array([3, 4, 5, 6])

In [ ]:
#OTHER WAYS TO GENERATE AN ARRAY
np.fromfunction(lambda i,j:i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
#the number of elements in an array
arr.size

4

In [ ]:
np.fromfunction(lambda i,j:i*j,shape=(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
#from the iterables also array can be generated
iterable=(i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
#from the string also array can be generated
np.fromstring("1,2,3,4",sep=",")

array([1., 2., 3., 4.])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
#range cannot deal with float variable
list(range(1.0,2,10))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
#when we have a fraction value in numpy we do:-
np.arange(0.1,10.2,0.2) #here 0.2 is the jump and read as START from 0.1 AND END AT 10.2

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [ ]:
np.linspace(1,5,20)#read as "GENERATE THE VALUE THAT START FROM 1 & ENDS WITH 5 AND THEN GIVE ME 20 VALUES BTW 1 TO 5"

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
np.logspace(1,5,10,base=2)#start from 1 end at 5 and total of 10 numbers btw them  with log of each with a base of two

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [ ]:
#zeros
arr1=np.zeros(5)
arr1.shape

(5,)

In [ ]:
arr2=np.zeros((3,4)) #read as 3 rows and 4 columns
arr2.shape

(3, 4)

In [ ]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr2.ndim

2

In [ ]:
#all the numbers interms of ones:-
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
arr=np.ones((3,4))

In [ ]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#if you want to add 5 to all the elements of the array
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
#numpy advanvce:-
arr=np.ones((3,4))#3 rows and 4 columns

In [ ]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [ ]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [ ]:
np.empty((3,4))#it will give us an array but with some random values,

array([[4.93933067e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [ ]:
#if we use int in the above the decimal will get converted to the integer
np.empty((3,4),int)

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [ ]:
#eye generates digonal matrix with 1 in digonal and 0 elsewhere:-
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[0]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 0}, axis=1)
              .sort_values(0, ascending=True))
  xs = counted[0]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values(0, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(0)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[1]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 1}, axis=1)
              .sort_values(1, ascending=True))
  xs = counted[1]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values(1, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(1)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[2]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 2}, axis=1)
              .sort_values(2, ascending=True))
  xs = counted[2]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_2.sort_values(2, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(2)
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series[3]
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 3}, axis=1)
              .sort_values(3, ascending=True))
  xs = counted[3]
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values(3, ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel(3)
_ = plt.ylabel('count()')

In [ ]:
#extra topics
import random #random can generate random numbers

In [ ]:
random.choice((1,2,3,45,6))

3

In [ ]:
random.choice("Ajay")

'A'

In [ ]:
#for generating a random number in the range:-
random.randrange(1,10)

5

In [ ]:
#if i want 3 random numbers btw 1 to 10:-
random.randrange(1,10,3)

7

In [ ]:
#for shuffling the values
list=[1,2,3,4,5]
random.shuffle(list)

In [ ]:
list

[3, 1, 4, 2, 5]

In [ ]:
#for uniform distribution
random.uniform(7,14)

11.079028889679357

In [ ]:
random.random()#a random number generated between a(included), 1 will be excluded

0.11401398371552629

In [ ]:
#when numpy came it said y to use different library use numpy instead
np.random.rand(2,3)

array([[0.73333217, 0.49197419, 0.15399087],
       [0.15291368, 0.49443976, 0.09571106]])

In [ ]:
np.random.rand(1)

array([0.99797106])

In [ ]:
#for normal distribution:-
np.random.randn(2,3)

array([[ 0.41222619,  0.44506998, -0.4528727 ],
       [-1.23029507,  0.06270479, -0.15051991]])

In [ ]:
#to get anything btw zero and one
np.random.random_sample()

0.5923623625595649

In [ ]:
#generate random integer from 1 to 5 with 3 rows and 4 columns
np.random.randint(1,5,size=(3,4))

array([[3, 2, 1, 3],
       [3, 3, 1, 1],
       [4, 2, 3, 3]])

In [3]:
arr=np.random.randint(1,5,size=(3,4))

In [ ]:
arr.size

12

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.reshape(2,6) #arraysize cannot change,multiples of array size

array([[3, 4, 1, 1, 1, 2],
       [4, 4, 1, 4, 3, 1]])

In [ ]:
#if u want 1 dimension:-
arr.reshape(12)

In [4]:
#you know the rows but you dont have the idea about the columns Numpy will automatically take care of it:-
arr.reshape(4,-1)

array([[3, 1, 2],
       [2, 2, 2],
       [4, 1, 2],
       [1, 1, 2]])

In [5]:
#inpace of -1 if we put any value it will treat it as -1 only
arr.reshape(4,-1000)

array([[3, 1, 2],
       [2, 2, 2],
       [4, 1, 2],
       [1, 1, 2]])

In [6]:
#you atleast have to know about one dimension
arr.reshape(-1,3)

array([[3, 1, 2],
       [2, 2, 2],
       [4, 1, 2],
       [1, 1, 2]])

In [7]:
arr.reshape(3,4).base

array([[3, 1, 2, 2],
       [2, 2, 4, 1],
       [2, 1, 1, 2]])