<a href="https://colab.research.google.com/github/omkarpattnaik8080/NUMPY01/blob/main/Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
l=[1,2,3,4,5]

In [6]:
ar=np.array(l)

In [7]:
ar

array([1, 2, 3, 4, 5])

In [8]:
type(ar)

numpy.ndarray

In [9]:
#agar list ke andar list hai yeah basically aek 2d array dega:-
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [10]:
#conversion of a list into an array using asarray
a=[1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [11]:
#usage of matrix fn(which is by default 2dimensional)
a=[2,3,4,5]
np.asarray(a)

array([2, 3, 4, 5])

In [12]:
b=np.matrix(a)

In [13]:
b

matrix([[2, 3, 4, 5]])

In [14]:
#important concept
a=np.array([2,3,4,5])

In [15]:
a

array([2, 3, 4, 5])

In [16]:
c=a

In [17]:
c

array([2, 3, 4, 5])

In [18]:
c[0]=100

In [19]:
c

array([100,   3,   4,   5])

In [20]:
a

array([100,   3,   4,   5])

In [21]:
d=np.copy(a)

In [22]:
d

array([100,   3,   4,   5])

In [23]:
a[1]=400

In [24]:
a

array([100, 400,   4,   5])

In [25]:
#fromfunction()

In [26]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
#fromiter() for iterable variable
iterable=(i*i for i in range(5))

In [28]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [39]:
np.fromstring('234 234', sep=' ')

array([234., 234.])

In [44]:
np.fromstring('4,5',sep=',')

array([4., 5.])

In [41]:
#numpy datatypes

In [42]:
l=[2,3,4,5,6]

In [43]:
ar=np.array(l)

In [33]:
ar

array([1, 2, 3, 4, 5])

In [34]:
ar.ndim

1

In [35]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [36]:
ar2.ndim

2

In [37]:
ar.size

5