<a href="https://colab.research.google.com/github/omkarpattnaik8080/NUMPY01/blob/main/Numpy001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [4]:
ar=np.array(l)

In [5]:
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]]) #for a 2dimensional array

array([[1, 2],
       [3, 4]])

In [9]:
a=[2,3,4]

In [11]:
np.asarray(a) #also can be used to convert normal list into array and #ASANYARRAY WORKS THE SAME

array([2, 3, 4])

In [12]:
#MATRIX
#yeah bydefault 2d hota hai
b=np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
#THERE WILL BE NO CONVERSION IF I USE ASANYARRAY WITH b BCZ ITS ALREADY A ARRAY MATRIX IS A SUBSET OF ARRAY
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a=np.array(l)

In [16]:
a

array([1, 2, 3, 4])